const { COLLECTIONS, ROLES, ACTIVE_ASSIGNMENT_STATUSES, MISSION_TRANSITIONS } = require("../config/constants");
const { db, loadActor, requireRole } = require("../auth/guards");
const { FieldValue } = require("../config/firebase");
const { invalid, notFound, conflict } = require("../utils/errors");
const { writeAudit } = require("../audit/writeAudit");

const transitionMissionStatus = async (context, data) => {
  const actor = await loadActor(context); requireRole(actor, [ROLES.DRIVER]); if (actor.accountStatus !== "Approved") conflict("Only approved Drivers can update mission status.", "account-inactive");
  const assignmentId = String(data?.assignmentId || ""); const nextStatus = String(data?.nextStatus || ""); const checklistId = String(data?.checklistId || ""); const notes = String(data?.notes || "").trim(); if (!assignmentId || !nextStatus) invalid("Assignment and next mission status are required.");
  await db().runTransaction(async (transaction) => {
    const assignmentRef = db().collection(COLLECTIONS.DRIVER_ASSIGNMENTS).doc(assignmentId); const assignmentSnapshot = await transaction.get(assignmentRef); if (!assignmentSnapshot.exists) notFound("This assignment no longer exists."); const assignment = assignmentSnapshot.data(); if (assignment.driverId !== actor.id) conflict("This assignment belongs to another Driver.", "permission-denied"); const current = assignment.missionStatus || assignment.status; if (!(MISSION_TRANSITIONS[current] || []).includes(nextStatus)) conflict("This mission transition is not allowed.", "invalid-status-transition");
    if (nextStatus === "Accepted") { if (!checklistId) invalid("Complete the vehicle readiness checklist before accepting."); const checklist = await transaction.get(db().collection(COLLECTIONS.VEHICLE_CHECKLISTS).doc(checklistId)); if (!checklist.exists || checklist.data().driverId !== actor.id || checklist.data().assignmentId !== assignmentId || checklist.data().vehicleId !== assignment.vehicleId || checklist.data().ready !== true) conflict("Complete the vehicle readiness checklist before accepting.", "vehicle-unavailable"); }
    const requestRef = db().collection(COLLECTIONS.TRANSPORT_REQUESTS).doc(assignment.requestId); const requestSnapshot = await transaction.get(requestRef); if (!requestSnapshot.exists) notFound("The linked request no longer exists."); const request = requestSnapshot.data(); if (["Cancelled", "Rejected", "Completed"].includes(request.status)) conflict("This request is no longer active.", "invalid-status-transition");
    const patch = { status: nextStatus === "Completed" ? "Completed" : "In Progress", missionStatus: nextStatus, updatedAt: FieldValue.serverTimestamp() }; const requestPatch = { status: nextStatus === "Completed" ? "Completed" : "In Progress", missionStatus: nextStatus, updatedAt: FieldValue.serverTimestamp() }; const field = { Accepted: "acceptedAt", "En Route": "enRouteAt", Arrived: "arrivedAt", "Picked Up": "pickedUpAt", Completed: "completedAt", Declined: "declinedAt" }[nextStatus]; if (field) { patch[field] = FieldValue.serverTimestamp(); requestPatch[field] = FieldValue.serverTimestamp(); } if (nextStatus === "Completed") { patch.completionNotes = notes; requestPatch.completedBy = actor.id; const vehicleRef = db().collection(COLLECTIONS.VEHICLES).doc(assignment.vehicleId); transaction.update(vehicleRef, { status: "Available", assignedRequestId: "", updatedAt: FieldValue.serverTimestamp() }); } if (nextStatus === "Declined") { patch.declineReason = notes; requestPatch.status = "Pending"; requestPatch.missionStatus = null; requestPatch.assignedDriverId = null; requestPatch.assignedVehicleId = null; requestPatch.lastDeclinedDriverId = actor.id; requestPatch.lastDeclineReason = notes; const vehicleRef = db().collection(COLLECTIONS.VEHICLES).doc(assignment.vehicleId); transaction.update(vehicleRef, { status: "Available", assignedRequestId: "", updatedAt: FieldValue.serverTimestamp() }); }
    transaction.update(assignmentRef, patch); transaction.update(requestRef, { ...requestPatch, timeline: { ...(request.timeline || {}), [nextStatus.toLowerCase().replace(/\s+/g, "_")]: { actorId: actor.id, actorRole: ROLES.DRIVER, note: notes, at: FieldValue.serverTimestamp() } } }); writeAudit(transaction, { action: "mission-status-transitioned", actor, targetType: "driverAssignment", targetId: assignmentId, assignmentId, requestId: assignment.requestId, summary: `Mission transitioned from ${current} to ${nextStatus}.`, before: { missionStatus: current }, after: { missionStatus: nextStatus } });
  });
  return { nextStatus };
};
module.exports = { transitionMissionStatus };