const { COLLECTIONS, ROLES, PERMISSIONS } = require("../config/constants");
const { db, loadActor, requireRole, requirePermission, requireServiceArea } = require("../auth/guards");
const { FieldValue } = require("../config/firebase");
const { invalid, notFound, conflict } = require("../utils/errors");
const { writeAudit } = require("../audit/writeAudit");

const cancelResidentRequest = async (context, data) => {
  const actor = await loadActor(context); requireRole(actor, [ROLES.RESIDENT]); const requestId = String(data?.requestId || ""); const reason = String(data?.reason || "").trim(); if (!requestId || reason.length < 3) invalid("A request and cancellation reason are required.");
  await db().runTransaction(async (transaction) => { const requestRef = db().collection(COLLECTIONS.TRANSPORT_REQUESTS).doc(requestId); const snapshot = await transaction.get(requestRef); if (!snapshot.exists) notFound(); const request = snapshot.data(); if (request.residentId !== actor.id) conflict("You can only cancel your own request.", "permission-denied"); if (!["Pending", "Assigned"].includes(request.status)) conflict("This request can no longer be cancelled.", "invalid-status-transition"); const assignments = await transaction.get(db().collection(COLLECTIONS.DRIVER_ASSIGNMENTS).where("requestId", "==", requestId)); assignments.docs.filter((item) => item.data().status === "Assigned").forEach((item) => { transaction.update(item.ref, { status: "Cancelled", cancellationReason: reason, cancelledAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); const vehicleId = item.data().vehicleId; if (vehicleId) transaction.update(db().collection(COLLECTIONS.VEHICLES).doc(vehicleId), { status: "Available", assignedRequestId: "", updatedAt: FieldValue.serverTimestamp() }); }); transaction.update(requestRef, { status: "Cancelled", cancellationReason: reason, cancelledBy: actor.id, cancelledAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), timeline: { ...(request.timeline || {}), cancelled: { actorId: actor.id, actorRole: ROLES.RESIDENT, note: reason, at: FieldValue.serverTimestamp() } } }); writeAudit(transaction, { action: "resident-request-cancelled", actor, targetType: "transportRequest", targetId: requestId, requestId, summary: "Resident cancelled their request.", metadata: { reason } }); }); return { cancelled: true };
};

const updateRequestPriority = async (context, data) => {
  const actor = await loadActor(context); requireRole(actor, [ROLES.ADMIN, ROLES.DISPATCHER]); requirePermission(actor, PERMISSIONS.UPDATE_REQUESTS); const requestId = String(data?.requestId || ""); const priority = String(data?.priority || ""); const reason = String(data?.reason || "").trim(); if (!["Emergency", "Urgent", "Non-Urgent", "Planned"].includes(priority) || reason.length < 3) invalid("A supported priority and reason are required."); await db().runTransaction(async (transaction) => { const ref = db().collection(COLLECTIONS.TRANSPORT_REQUESTS).doc(requestId); const snap = await transaction.get(ref); if (!snap.exists) notFound(); const request = snap.data(); requireServiceArea(actor, request.barangay); if (["Completed", "Cancelled", "Rejected"].includes(request.status)) conflict("This request cannot be reprioritized.", "invalid-status-transition"); transaction.update(ref, { priorityLevel: priority, previousPriority: request.priorityLevel || request.level || "", priorityUpdatedBy: actor.id, priorityUpdateReason: reason, priorityUpdatedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); writeAudit(transaction, { action: "request-priority-updated", actor, targetType: "transportRequest", targetId: requestId, requestId, summary: `Request priority set to ${priority}.`, before: { priority: request.priorityLevel || request.level }, after: { priority }, metadata: { reason } }); }); return { priority };
};

const rejectRequest = async (context, data) => {
  const actor = await loadActor(context); requireRole(actor, [ROLES.ADMIN, ROLES.DISPATCHER]); requirePermission(actor, PERMISSIONS.UPDATE_REQUESTS); const requestId = String(data?.requestId || ""); const reason = String(data?.reason || "").trim(); if (reason.length < 3) invalid("A rejection reason is required."); await db().runTransaction(async (transaction) => { const ref = db().collection(COLLECTIONS.TRANSPORT_REQUESTS).doc(requestId); const snap = await transaction.get(ref); if (!snap.exists) notFound(); const request = snap.data(); requireServiceArea(actor, request.barangay); if (request.status !== "Pending") conflict("Only unassigned requests can be rejected.", "request-not-assignable"); transaction.update(ref, { status: "Rejected", rejectedBy: actor.id, rejectedAt: FieldValue.serverTimestamp(), rejectionReason: reason, updatedAt: FieldValue.serverTimestamp() }); writeAudit(transaction, { action: "request-rejected", actor, targetType: "transportRequest", targetId: requestId, requestId, summary: "Request rejected by operations staff.", metadata: { reason } }); }); return { rejected: true };
};
module.exports = { cancelResidentRequest, updateRequestPriority, rejectRequest };