import { FontAwesome } from "@expo/vector-icons";
import { Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import AppButton from "../../../components/ui/AppButton";
import { COLORS, RADIUS, SPACING } from "../../../constants/design";
import { canResidentCancel, formatRequestDate, getDestinationCoordinates, getDestinationLabel, getPickupCoordinates, getPickupLabel, getRequestStatusMeta } from "../utils/requestMapper";
import RequestStatusTimeline from "./RequestStatusTimeline";
import LeafletMap from "../../../components/LeafletMap";

const DetailLine = ({ label, value }) => <View style={styles.detailLine}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value || "Not provided"}</Text></View>;

export default function ResidentRequestDetails({ request, visible, onClose, onCancel }) {
  if (!request) return null;
  const status = getRequestStatusMeta(request.status);
  const driverName = request.assignedDriverName || request.driverName;
  const vehicle = request.assignedVehicleName || request.vehicle;
  const dispatcherName = request.dispatcherName || request.assignedDispatcherName;
  const pickupCoordinates = getPickupCoordinates(request);
  const destinationCoordinates = getDestinationCoordinates(request);
  const groups = Object.entries(request.vulnerableGroups || {}).filter(([, value]) => value).map(([key]) => key.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase()).replace("Pwd", "PWD"));

  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.card}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Close request details" style={styles.close} onPress={onClose}><Text style={styles.closeText}>X</Text></TouchableOpacity><Text style={styles.title}>Request details</Text><Text style={styles.reference}>{request.reference}</Text><View style={[styles.status, { backgroundColor: status.tone === "danger" ? COLORS.emergencySurface : status.tone === "success" ? "#E7F5ED" : COLORS.warningSurface }]}><FontAwesome name={status.icon} size={14} color={status.tone === "danger" ? COLORS.emergency : status.tone === "success" ? COLORS.success : COLORS.warning} /><Text style={styles.statusText}>{status.label}</Text></View>
  <DetailLine label="Request type" value={request.serviceType || request.emergencyType} /><DetailLine label="Category" value={request.category || request.requestType} /><DetailLine label="Pickup" value={getPickupLabel(request)} /><DetailLine label="Pickup details" value={request.pickupDetails} /><DetailLine label="Destination" value={getDestinationLabel(request)} /><DetailLine label="Passenger" value={`${request.passengerName || request.residentName || "Not provided"}${request.passengerCapacity ? ` (${request.passengerCapacity})` : ""}`} /><DetailLine label="Contact number" value={request.contactNumber} /><DetailLine label="Transport need" value={request.description || request.summary} /><DetailLine label="Assistance" value={groups.join(", ") || request.accessibilityNotes} /><DetailLine label="Submitted" value={formatRequestDate(request.createdAt)} /><DetailLine label="Latest update" value={formatRequestDate(request.latestUpdatedAt)} />
  <View style={styles.section}><Text style={styles.sectionTitle}>Assigned responder</Text>{driverName ? <><DetailLine label="Driver" value={driverName} /><DetailLine label="Vehicle" value={[vehicle, request.vehiclePlateNumber ? `Plate ${request.vehiclePlateNumber}` : ""].filter(Boolean).join(" | ")} /><DetailLine label="Contact" value={request.assignedDriverPhone || request.driverContactNumber || "Contact is not available yet"} /></> : <Text style={styles.muted}>Not yet assigned. Dispatcher contact is shown only when linked to this request.</Text>}{dispatcherName ? <><DetailLine label="Dispatcher" value={dispatcherName} /><DetailLine label="Dispatcher contact" value={request.dispatcherOfficePhone || "Contact is not available yet"} /></> : null}</View>
  {pickupCoordinates || destinationCoordinates ? <View style={styles.map}><LeafletMap title={`Route for ${request.reference}`} pickupLabel={getPickupLabel(request)} destinationLabel={getDestinationLabel(request)} pickupCoordinates={pickupCoordinates} destinationCoordinates={destinationCoordinates} /></View> : null}
  <View style={styles.section}><Text style={styles.sectionTitle}>Status timeline</Text><RequestStatusTimeline request={request} /></View>
  {canResidentCancel(request) ? <AppButton label="Cancel request" variant="danger" onPress={() => onCancel(request)} style={styles.cancel} /> : null}</ScrollView></View></View></Modal>;
}

const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(13,31,24,.62)" }, card: { maxHeight: "94%", backgroundColor: COLORS.surface, borderTopLeftRadius: RADIUS.lg, borderTopRightRadius: RADIUS.lg }, content: { padding: SPACING.lg, paddingBottom: 32 }, close: { alignSelf: "flex-end", width: 36, height: 36, justifyContent: "center", alignItems: "center" }, closeText: { fontSize: 17, fontWeight: "800", color: COLORS.text }, title: { fontSize: 22, fontWeight: "800", color: COLORS.text }, reference: { marginTop: 4, color: COLORS.mutedText, fontSize: 13, fontWeight: "700" }, status: { alignSelf: "flex-start", flexDirection: "row", gap: 7, marginTop: SPACING.md, paddingHorizontal: 10, paddingVertical: 7, borderRadius: RADIUS.pill }, statusText: { color: COLORS.text, fontSize: 13, fontWeight: "700" }, detailLine: { marginTop: SPACING.md }, label: { color: COLORS.subtleText, fontSize: 12, fontWeight: "700", textTransform: "uppercase" }, value: { marginTop: 3, color: COLORS.text, fontSize: 15, lineHeight: 21 }, section: { marginTop: SPACING.xl, paddingTop: SPACING.md, borderTopWidth: 1, borderTopColor: COLORS.border }, sectionTitle: { color: COLORS.text, fontSize: 17, fontWeight: "800" }, muted: { marginTop: SPACING.sm, color: COLORS.mutedText, lineHeight: 20 }, map: { height: 260, marginTop: SPACING.xl, overflow: "hidden", borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.sm }, cancel: { marginTop: SPACING.xl } });
