export const TOLEDO_BARANGAY_OPTIONS = [
  { label: "Awihao, Toledo City", value: "Awihao, Toledo City" },
  { label: "Bagakay, Toledo City", value: "Bagakay, Toledo City" },
  { label: "Bato, Toledo City", value: "Bato, Toledo City" },
  { label: "Biga, Toledo City", value: "Biga, Toledo City" },
  { label: "Bulongan, Toledo City", value: "Bulongan, Toledo City" },
  { label: "Bunga, Toledo City", value: "Bunga, Toledo City" },
  { label: "Cabitoonan, Toledo City", value: "Cabitoonan, Toledo City" },
  { label: "Calongcalong, Toledo City", value: "Calongcalong, Toledo City" },
  { label: "Cambang-ug, Toledo City", value: "Cambang-ug, Toledo City" },
  { label: "Camp 8, Toledo City", value: "Camp 8, Toledo City" },
  { label: "Canlumampao, Toledo City", value: "Canlumampao, Toledo City" },
  { label: "Cantabaco, Toledo City", value: "Cantabaco, Toledo City" },
  { label: "Capitan Claudio, Toledo City", value: "Capitan Claudio, Toledo City" },
  { label: "Carmen, Toledo City", value: "Carmen, Toledo City" },
  { label: "Daanglungsod, Toledo City", value: "Daanglungsod, Toledo City" },
  { label: "Don Andres Soriano (Lutopan), Toledo City", value: "Don Andres Soriano (Lutopan), Toledo City" },
  { label: "Dumlog, Toledo City", value: "Dumlog, Toledo City" },
  { label: "Gen. Climaco (Malubog), Toledo City", value: "Gen. Climaco (Malubog), Toledo City" },
  { label: "Ibo, Toledo City", value: "Ibo, Toledo City" },
  { label: "Ilihan, Toledo City", value: "Ilihan, Toledo City" },
  { label: "Juan Climaco, Sr. (Magdugo), Toledo City", value: "Juan Climaco, Sr. (Magdugo), Toledo City" },
  { label: "Landahan, Toledo City", value: "Landahan, Toledo City" },
  { label: "Loay, Toledo City", value: "Loay, Toledo City" },
  { label: "Luray II, Toledo City", value: "Luray II, Toledo City" },
  { label: "Matab-ang, Toledo City", value: "Matab-ang, Toledo City" },
  { label: "Media Once, Toledo City", value: "Media Once, Toledo City" },
  { label: "Pangamihan, Toledo City", value: "Pangamihan, Toledo City" },
  { label: "Poblacion, Toledo City", value: "Poblacion, Toledo City" },
  { label: "Poog, Toledo City", value: "Poog, Toledo City" },
  { label: "Putingbato, Toledo City", value: "Putingbato, Toledo City" },
  { label: "Sagay, Toledo City", value: "Sagay, Toledo City" },
  { label: "Sam-ang, Toledo City", value: "Sam-ang, Toledo City" },
  { label: "Sangi, Toledo City", value: "Sangi, Toledo City" },
  { label: "Santo Nino (Mainggit), Toledo City", value: "Santo Nino (Mainggit), Toledo City" },
  { label: "Subayon, Toledo City", value: "Subayon, Toledo City" },
  { label: "Talavera, Toledo City", value: "Talavera, Toledo City" },
  { label: "Tubod, Toledo City", value: "Tubod, Toledo City" },
  { label: "Tungkay, Toledo City", value: "Tungkay, Toledo City" },
];
