import { useRef, useState } from "react";
import { Linking, Modal, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Dropdown } from "react-native-element-dropdown";
import AppButton from "../../../components/ui/AppButton";
import FeedbackMessage from "../../../components/ui/FeedbackMessage";
import { COLORS, RADIUS, SPACING } from "../../../constants/design";
import { MISSION_STATUSES } from "../../../constants/app";
import { acceptAssignment, advanceMission, declineAssignment, saveVehicleChecklist } from "../services/driverMissionService";
import { getDestinationCoordinates, getDestinationLabel, getMissionStatus, getPickupCoordinates, getPickupLabel } from "../utils/driverMissionMapper";
import { COMPLETION_OUTCOMES, DECLINE_REASONS, REQUIRED_CHECKLIST_ITEMS, isChecklistReady, validateCompletion, validateDecline } from "../utils/driverMissionValidation";

const labels = { fuel: "Fuel level sufficient", tires: "Tires checked", brakes: "Brakes functional", lights: "Lights and signals working", firstAidKit: "First-aid kit available", communicationDevice: "Communication device working", documents: "Vehicle documents available", cleanliness: "Vehicle clean and safe", emergencyEquipment: "Emergency equipment available" };
const blankItems = () => Object.fromEntries(REQUIRED_CHECKLIST_ITEMS.map((key) => [key, false]));

export default function DriverMissionActions({ assignment, driverId, onFeedback }) {
  const [checklistOpen, setChecklistOpen] = useState(false); const [declineOpen, setDeclineOpen] = useState(false); const [completeOpen, setCompleteOpen] = useState(false); const [items, setItems] = useState(blankItems); const [issues, setIssues] = useState(""); const [reason, setReason] = useState(""); const [details, setDetails] = useState(""); const [outcome, setOutcome] = useState(""); const [notes, setNotes] = useState(""); const [completionIssues, setCompletionIssues] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const savingRef = useRef(false);
  const status = getMissionStatus(assignment); const request = assignment.currentRequest || assignment.request || {}; const pickup = getPickupLabel(request); const destination = getDestinationLabel(request);
  const run = async (action, success) => { if (savingRef.current) return; savingRef.current = true; setSaving(true); setError(""); try { await action(); onFeedback?.(success, "success"); } catch (e) { setError(e?.message || "The mission update could not be saved. Try again."); } finally { savingRef.current = false; setSaving(false); } };
  const openMap = async (coordinates, address) => { const target = coordinates ? `https://www.google.com/maps/search/?api=1&query=${coordinates[0]},${coordinates[1]}` : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`; try { if (await Linking.canOpenURL(target)) await Linking.openURL(target); else onFeedback?.("A maps application is not available on this device.", "warning"); } catch { onFeedback?.("The map link could not be opened.", "warning"); } };
  const accept = async () => { if (!isChecklistReady(items)) { setError("All safety items must pass before the vehicle can be marked ready."); return; } await run(async () => { const checklistId = await saveVehicleChecklist({ driverId, assignment, items, issues }); await acceptAssignment({ assignmentId: assignment.id, driverId, checklistId }); setChecklistOpen(false); }, "Assignment accepted. Mark En Route when you are ready to depart."); };
  const decline = () => { if (!validateDecline(reason, details)) { setError(reason === "Other" ? "Describe the other decline reason (3-300 characters)." : "Choose a reason and keep the explanation within 300 characters."); return; } run(async () => { await declineAssignment({ assignmentId: assignment.id, driverId, reason, details }); setDeclineOpen(false); }, "Assignment declined. Dispatch must reassign the request."); };
  const complete = () => { if (!validateCompletion(outcome, notes)) { setError("Choose an outcome and enter completion notes (1-500 characters)."); return; } run(async () => { await advanceMission({ assignmentId: assignment.id, driverId, nextStatus: MISSION_STATUSES.COMPLETED, completion: { outcome, notes: notes.trim(), issues: completionIssues.trim() } }); setCompleteOpen(false); }, "Mission completed successfully."); };
  const move = (next, message) => run(() => advanceMission({ assignmentId: assignment.id, driverId, nextStatus: next, completion: {} }), message);
  return <><View style={styles.locations}><AppButton label="Open pickup" variant="secondary" onPress={() => openMap(getPickupCoordinates(request), pickup)} style={styles.locationButton} /><AppButton label="Open destination" variant="secondary" onPress={() => openMap(getDestinationCoordinates(request), destination)} style={styles.locationButton} /></View><View style={styles.actions}>{status === MISSION_STATUSES.ASSIGNED ? <><AppButton label="Review vehicle" onPress={() => { setItems(blankItems()); setIssues(""); setError(""); setChecklistOpen(true); }} style={styles.action} /><AppButton label="Decline" variant="danger" onPress={() => { setReason(""); setDetails(""); setError(""); setDeclineOpen(true); }} style={styles.action} /></> : null}{status === MISSION_STATUSES.ACCEPTED ? <AppButton label="Mark en route" onPress={() => move(MISSION_STATUSES.EN_ROUTE, "Mission marked en route.")} loading={saving} style={styles.full} /> : null}{status === MISSION_STATUSES.EN_ROUTE ? <AppButton label="Confirm arrival" onPress={() => move(MISSION_STATUSES.ARRIVED, "Arrival recorded.")} loading={saving} style={styles.full} /> : null}{status === MISSION_STATUSES.ARRIVED ? <AppButton label="Confirm pickup" onPress={() => move(MISSION_STATUSES.PICKED_UP, "Passenger pickup recorded.")} loading={saving} style={styles.full} /> : null}{status === MISSION_STATUSES.PICKED_UP ? <AppButton label="Complete mission" onPress={() => { setOutcome(""); setNotes(""); setCompletionIssues(""); setError(""); setCompleteOpen(true); }} style={styles.full} /> : null}</View>
<Modal visible={checklistOpen} transparent animationType="slide" onRequestClose={() => !saving && setChecklistOpen(false)}><View style={styles.overlay}><View style={styles.modal}><ScrollView><Text style={styles.title}>Vehicle readiness</Text><Text style={styles.subtitle}>Complete every safety check before accepting this assignment.</Text>{REQUIRED_CHECKLIST_ITEMS.map((key) => <View key={key} style={styles.toggle}><Text style={styles.toggleText}>{labels[key]}</Text><Switch value={items[key]} onValueChange={(value) => setItems((current) => ({ ...current, [key]: value }))} trackColor={{ false: COLORS.disabled, true: COLORS.primary }} /></View>)}<TextInput style={styles.input} value={issues} onChangeText={setIssues} placeholder="Reported issues (optional)" multiline maxLength={500} textAlignVertical="top" />{error ? <FeedbackMessage message={error} tone="error" /> : null}<View style={styles.row}><AppButton label="Cancel" variant="secondary" onPress={() => setChecklistOpen(false)} style={styles.action} /><AppButton label="Accept assignment" loading={saving} onPress={accept} style={styles.action} /></View></ScrollView></View></View></Modal>
<Modal visible={declineOpen} transparent animationType="fade" onRequestClose={() => !saving && setDeclineOpen(false)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.title}>Decline assignment</Text><Text style={styles.subtitle}>Dispatch must select another driver after this is saved.</Text><Dropdown style={styles.dropdown} data={DECLINE_REASONS.map((value) => ({ label: value, value }))} labelField="label" valueField="value" value={reason} onChange={(item) => setReason(item.value)} placeholder="Choose reason" /><TextInput style={styles.input} value={details} onChangeText={setDetails} placeholder={reason === "Other" ? "Describe the reason" : "Optional explanation"} multiline maxLength={300} textAlignVertical="top" />{error ? <FeedbackMessage message={error} tone="error" /> : null}<View style={styles.row}><AppButton label="Keep assignment" variant="secondary" onPress={() => setDeclineOpen(false)} style={styles.action} /><AppButton label="Confirm decline" variant="danger" loading={saving} onPress={decline} style={styles.action} /></View></View></View></Modal>
<Modal visible={completeOpen} transparent animationType="slide" onRequestClose={() => !saving && setCompleteOpen(false)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.title}>Complete mission</Text><Dropdown style={styles.dropdown} data={COMPLETION_OUTCOMES.map((value) => ({ label: value, value }))} labelField="label" valueField="value" value={outcome} onChange={(item) => setOutcome(item.value)} placeholder="Choose outcome" /><TextInput style={styles.input} value={notes} onChangeText={setNotes} placeholder="Completion notes" multiline maxLength={500} textAlignVertical="top" /><TextInput style={styles.input} value={completionIssues} onChangeText={setCompletionIssues} placeholder="Issues encountered (optional)" multiline maxLength={300} textAlignVertical="top" />{error ? <FeedbackMessage message={error} tone="error" /> : null}<View style={styles.row}><AppButton label="Back" variant="secondary" onPress={() => setCompleteOpen(false)} style={styles.action} /><AppButton label="Confirm completion" loading={saving} onPress={complete} style={styles.action} /></View></View></View></Modal></>;
}
const styles=StyleSheet.create({locations:{flexDirection:"row",gap:SPACING.sm,marginTop:SPACING.md},locationButton:{flex:1,minHeight:42,paddingHorizontal:8},actions:{marginTop:SPACING.md},full:{width:"100%"},row:{flexDirection:"row",gap:SPACING.sm,marginTop:SPACING.lg},action:{flex:1},overlay:{flex:1,justifyContent:"center",padding:SPACING.lg,backgroundColor:"rgba(13,31,24,.62)"},modal:{width:"100%",maxWidth:560,maxHeight:"90%",alignSelf:"center",padding:SPACING.lg,borderRadius:RADIUS.md,backgroundColor:COLORS.surface},title:{color:COLORS.text,fontSize:21,fontWeight:"800"},subtitle:{marginTop:5,color:COLORS.mutedText,lineHeight:20},toggle:{minHeight:48,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderColor:COLORS.border},toggleText:{flex:1,paddingRight:10,color:COLORS.text,fontSize:14},input:{minHeight:76,marginTop:SPACING.md,padding:SPACING.md,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.sm,color:COLORS.text},dropdown:{minHeight:50,marginTop:SPACING.md,paddingHorizontal:SPACING.md,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.sm}});
