import { useRef, useState } from "react";
import { Modal, StyleSheet, Text, TextInput, View } from "react-native";
import { Dropdown } from "react-native-element-dropdown";
import AppButton from "../../../components/ui/AppButton";
import FeedbackMessage from "../../../components/ui/FeedbackMessage";
import { COLORS, DESIGN_COLORS, RADIUS, SPACING } from "../../../constants/design";
import { MISSION_STATUSES } from "../../../constants/app";
import { acceptAssignment, advanceMission, declineAssignment } from "../services/driverMissionService";
import DriverRideSteps from "./DriverRideSteps";
import { getMissionStatus } from "../utils/driverMissionMapper";
import { COMPLETION_OUTCOMES, DECLINE_REASONS, validateCompletion, validateDecline } from "../utils/driverMissionValidation";

export default function DriverMissionActions({ assignment, driverId, onFeedback }) {
  const [declineOpen, setDeclineOpen] = useState(false); const [completeOpen, setCompleteOpen] = useState(false); const [reason, setReason] = useState(""); const [details, setDetails] = useState(""); const [outcome, setOutcome] = useState(""); const [notes, setNotes] = useState(""); const [completionIssues, setCompletionIssues] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const savingRef = useRef(false);
  const status = getMissionStatus(assignment);   const run = async (action, success) => { if (savingRef.current) return; savingRef.current = true; setSaving(true); setError(""); try { await action(); onFeedback?.(success, "success"); } catch (e) { setError(e?.message || "The mission update could not be saved. Try again."); } finally { savingRef.current = false; setSaving(false); } };
  // One tap accepts (driver-home-restyle-plan.md Piece 1). The vehicle checklist is no longer asked; old checklists stay saved.
  const accept = () => run(() => acceptAssignment({ assignmentId: assignment.id, driverId }), "Assignment accepted. Mark En Route when you are ready to depart.");
  const decline = () => { if (!validateDecline(reason, details)) { setError(reason === "Other" ? "Describe the other decline reason (3-300 characters)." : "Choose a reason and keep the explanation within 300 characters."); return; } run(async () => { await declineAssignment({ assignmentId: assignment.id, driverId, reason, details }); setDeclineOpen(false); }, "Assignment declined. Dispatch must reassign the request."); };
  const complete = () => { if (!validateCompletion(outcome, notes)) { setError("Choose an outcome and enter completion notes (1-500 characters)."); return; } run(async () => { await advanceMission({ assignmentId: assignment.id, driverId, nextStatus: MISSION_STATUSES.COMPLETED, completion: { outcome, notes: notes.trim(), issues: completionIssues.trim() } }); setCompleteOpen(false); }, "Mission completed successfully."); };
  const move = (next, message) => run(() => advanceMission({ assignmentId: assignment.id, driverId, nextStatus: next, completion: {} }), message);
  return <>{/* The "Navigate to pickup / destination" button is on the Map page now (DriverNavigateButton.jsx, driver-pages-plan.md Step 1). */}<View style={styles.actions}>{status === MISSION_STATUSES.ASSIGNED ? <><AppButton label="Accept ride" loading={saving} onPress={accept} style={styles.mainButton} textStyle={styles.buttonText} /><AppButton label="Decline" variant="secondary" disabled={saving} onPress={() => { setReason(""); setDetails(""); setError(""); setDeclineOpen(true); }} style={styles.declineButton} textStyle={[styles.buttonText, styles.declineText]} /></> : null}{status === MISSION_STATUSES.ACCEPTED ? <AppButton label="Mark en route" onPress={() => move(MISSION_STATUSES.EN_ROUTE, "Mission marked en route.")} loading={saving} style={styles.mainButton} textStyle={styles.buttonText} /> : null}{status === MISSION_STATUSES.EN_ROUTE ? <AppButton label="Confirm arrival" onPress={() => move(MISSION_STATUSES.ARRIVED, "Arrival recorded.")} loading={saving} style={styles.mainButton} textStyle={styles.buttonText} /> : null}{status === MISSION_STATUSES.ARRIVED ? <AppButton label="Confirm pickup" onPress={() => move(MISSION_STATUSES.PICKED_UP, "Passenger pickup recorded.")} loading={saving} style={styles.mainButton} textStyle={styles.buttonText} /> : null}{status === MISSION_STATUSES.PICKED_UP ? <AppButton label="Complete mission" onPress={() => { setOutcome(""); setNotes(""); setCompletionIssues(""); setError(""); setCompleteOpen(true); }} style={styles.mainButton} textStyle={styles.buttonText} /> : null}{/* Errors from Accept and the step buttons (e.g. "Tap Resume duty, then accept this ride."). The pop-ups show their own. */}{error && !declineOpen && !completeOpen ? <FeedbackMessage message={error} tone="error" /> : null}</View>{/* The "Ride steps" list, under the step button so the button stays on screen (driver-home-restyle-plan.md Piece 4b). Only after Accept. */}{status !== MISSION_STATUSES.ASSIGNED ? <DriverRideSteps assignment={assignment} status={status} /> : null}
<Modal visible={declineOpen} transparent animationType="fade" onRequestClose={() => !saving && setDeclineOpen(false)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.title}>Decline assignment</Text><Text style={styles.subtitle}>Dispatch must select another driver after this is saved.</Text><Dropdown style={styles.dropdown} data={DECLINE_REASONS.map((value) => ({ label: value, value }))} labelField="label" valueField="value" value={reason} onChange={(item) => setReason(item.value)} placeholder="Choose reason" /><TextInput style={styles.input} value={details} onChangeText={setDetails} placeholder={reason === "Other" ? "Describe the reason" : "Optional explanation"} multiline maxLength={300} textAlignVertical="top" />{error ? <FeedbackMessage message={error} tone="error" /> : null}<View style={styles.row}><AppButton label="Keep assignment" variant="secondary" onPress={() => setDeclineOpen(false)} style={styles.action} /><AppButton label="Confirm decline" variant="danger" loading={saving} onPress={decline} style={styles.action} /></View></View></View></Modal>
<Modal visible={completeOpen} transparent animationType="slide" onRequestClose={() => !saving && setCompleteOpen(false)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.title}>Complete mission</Text><Dropdown style={styles.dropdown} data={COMPLETION_OUTCOMES.map((value) => ({ label: value, value }))} labelField="label" valueField="value" value={outcome} onChange={(item) => setOutcome(item.value)} placeholder="Choose outcome" /><TextInput style={styles.input} value={notes} onChangeText={setNotes} placeholder="Completion notes" multiline maxLength={500} textAlignVertical="top" /><TextInput style={styles.input} value={completionIssues} onChangeText={setCompletionIssues} placeholder="Issues encountered (optional)" multiline maxLength={300} textAlignVertical="top" />{error ? <FeedbackMessage message={error} tone="error" /> : null}<View style={styles.row}><AppButton label="Back" variant="secondary" onPress={() => setCompleteOpen(false)} style={styles.action} /><AppButton label="Confirm completion" loading={saving} onPress={complete} style={styles.action} /></View></View></View></Modal></>;
}
const styles=StyleSheet.create({
actions:{},
// Accept on top, Decline underneath, both full width and 56 tall (DESIGN.md: never two equal buttons side by side).
// The step buttons (Mark en route...) use mainButton too.
mainButton:{width:"100%",minHeight:56,borderRadius:16,backgroundColor:DESIGN_COLORS.hallGreen},declineButton:{width:"100%",minHeight:56,marginTop:SPACING.md,borderRadius:16,borderWidth:1.5,borderColor:DESIGN_COLORS.controlOutline,backgroundColor:DESIGN_COLORS.paperWhite},buttonText:{fontSize:17,lineHeight:22,fontWeight:"700"},declineText:{color:DESIGN_COLORS.ink},row:{flexDirection:"row",gap:SPACING.sm,marginTop:SPACING.lg},action:{flex:1},overlay:{flex:1,justifyContent:"center",padding:SPACING.lg,backgroundColor:"rgba(13,31,24,.62)"},modal:{width:"100%",maxWidth:560,maxHeight:"90%",alignSelf:"center",padding:SPACING.lg,borderRadius:RADIUS.md,backgroundColor:COLORS.surface},title:{color:COLORS.text,fontSize:21,fontWeight:"800"},subtitle:{marginTop:5,color:COLORS.mutedText,lineHeight:20},input:{minHeight:76,marginTop:SPACING.md,padding:SPACING.md,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.sm,color:COLORS.text},dropdown:{minHeight:50,marginTop:SPACING.md,paddingHorizontal:SPACING.md,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.sm}});
