const { COLLECTIONS, ROLES, PERMISSIONS, ACTIVE_ASSIGNMENT_STATUSES } = require("../config/constants");
const { db, loadActor, requireRole, requirePermission } = require("../auth/guards");
const { FieldValue } = require("../config/firebase");
const { invalid, notFound, conflict } = require("../utils/errors");
const { writeAudit } = require("../audit/writeAudit");

const saveMaintenanceRecord = async (context, data) => {
  const actor = await loadActor(context); requireRole(actor, [ROLES.ADMIN]); requirePermission(actor, PERMISSIONS.MANAGE_VEHICLES); const vehicleId = String(data?.vehicleId || ""); const maintenanceType = String(data?.maintenanceType || "").trim(); const description = String(data?.description || "").trim(); const status = String(data?.status || ""); if (!vehicleId || maintenanceType.length < 2 || description.length < 3 || !["Reported", "Scheduled", "In Progress", "Completed", "Cancelled"].includes(status)) invalid("Vehicle, maintenance type, description, and status are required."); if (status === "Completed" && !data.completedAt) invalid("Completed maintenance requires a completion date."); await db().runTransaction(async (transaction) => { const vehicleRef = db().collection(COLLECTIONS.VEHICLES).doc(vehicleId); const vehicleSnapshot = await transaction.get(vehicleRef); if (!vehicleSnapshot.exists) notFound("This vehicle no longer exists."); const activeAssignments = await transaction.get(db().collection(COLLECTIONS.DRIVER_ASSIGNMENTS).where("vehicleId", "==", vehicleId)); if (["Scheduled", "In Progress"].includes(status) && activeAssignments.docs.some((item) => ACTIVE_ASSIGNMENT_STATUSES.has(item.data().status))) conflict("Resolve the active vehicle mission before maintenance.", "vehicle-unavailable"); const maintenanceRef = db().collection(COLLECTIONS.VEHICLE_MAINTENANCE).doc(); transaction.create(maintenanceRef, { vehicleId, maintenanceType, description, status, reportedIssues: String(data.reportedIssues || "").trim(), serviceProvider: String(data.serviceProvider || "").trim(), cost: Number(data.cost) || 0, completedAt: data.completedAt || null, nextServiceDate: data.nextServiceDate || null, createdBy: actor.id, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), authoritative: true }); transaction.update(vehicleRef, { maintenanceStatus: status, status: ["Reported", "Scheduled", "In Progress"].includes(status) ? "Under Maintenance" : vehicleSnapshot.data().status || "Inactive", updatedAt: FieldValue.serverTimestamp() }); writeAudit(transaction, { action: "vehicle-maintenance-recorded", actor, targetType: "vehicle", targetId: vehicleId, summary: "Vehicle maintenance recorded by trusted backend.", metadata: { maintenanceId: maintenanceRef.id, status } }); }); return { saved: true };
};
module.exports = { saveMaintenanceRecord };