import { collection, doc, getDocs, limit, query, runTransaction, serverTimestamp, setDoc, where } from "firebase/firestore";

import { ACCOUNT_STATUSES, FIRESTORE_COLLECTIONS, ROLE_OPTIONS, ROLES, VEHICLE_MAINTENANCE_STATUSES } from "../../../constants/app";
import { db } from "../../../firebase";

const ACTIVE_MISSION_STATUSES = ["Assigned", "In Progress", "Accepted", "En Route", "Arrived", "Picked Up"];
const ACTIVE_INVITATION_STATUS = "Pending Invitation";
const hasText = (value, minimum = 1) => typeof value === "string" && value.trim().length >= minimum;

export const getProfileName = (profile) => profile?.fullName || profile?.displayName || profile?.email || "Unnamed user";
export const getDate = (value) => (typeof value?.toDate === "function" ? value.toDate() : value ? new Date(value) : null);
export const isActiveMission = (assignment) => ACTIVE_MISSION_STATUSES.includes(assignment?.status || assignment?.missionStatus);
export const getUserMissionConflicts = (userId, assignments = []) => assignments.filter((assignment) => assignment.driverId === userId && isActiveMission(assignment));
export const sanitizeCsvValue = (value) => {
  const text = value == null ? "" : String(value).replace(/\r?\n/g, " ");
  const safeText = /^[=+\-@]/.test(text.trim()) ? `'${text}` : text;
  return `"${safeText.replace(/"/g, '""')}"`;
};

export const buildCsv = ({ title, generatedBy, filters, rows }) => {
  const metadata = [
    [title],
    ["Generated at", new Date().toLocaleString("en-PH")],
    ["Generated by", generatedBy || "Admin"],
    ["Filters", filters || "None"],
    [],
  ];
  return [...metadata, ...rows].map((row) => row.map(sanitizeCsvValue).join(",")).join("\r\n");
};

const writeActivity = (transaction, adminId, action, targetType, targetId, summary, metadata = {}) => {
  transaction.set(doc(collection(db, FIRESTORE_COLLECTIONS.ACTIVITY_LOGS)), {
    action,
    actorId: adminId,
    actorRole: ROLES.ADMIN,
    targetType,
    targetId,
    summary,
    metadata,
    createdAt: serverTimestamp(),
  });
};

export const reviewDriverApplication = async ({ adminId, applicationId, decision, reason = "", notes = "" }) => {
  if (!["Approved", "Rejected", "Under Review", "Correction Requested"].includes(decision)) {
    throw new Error("Choose a supported application decision.");
  }
  if (decision === "Rejected" && !hasText(reason, 3)) {
    throw new Error("A rejection reason of at least 3 characters is required.");
  }

  await runTransaction(db, async (transaction) => {
    const applicationRef = doc(db, FIRESTORE_COLLECTIONS.DRIVER_APPLICATIONS, applicationId);
    const applicationSnapshot = await transaction.get(applicationRef);
    if (!applicationSnapshot.exists()) throw new Error("The driver application no longer exists.");
    const application = applicationSnapshot.data();
    if (application.driverUid === adminId) throw new Error("You cannot review your own driver application.");
    if (["Approved", "Rejected"].includes(application.status) && application.status !== decision) {
      throw new Error("This application already has a final decision.");
    }
    const driverRef = doc(db, FIRESTORE_COLLECTIONS.USERS, application.driverUid);
    const driverSnapshot = await transaction.get(driverRef);
    if (!driverSnapshot.exists()) throw new Error("The linked Driver profile is unavailable.");

    const applicationPatch = {
      status: decision,
      approvalStatus: decision,
      reviewedAt: serverTimestamp(),
      reviewedBy: adminId,
      reviewNotes: notes.trim(),
      rejectionReason: decision === "Rejected" ? reason.trim() : "",
      updatedAt: serverTimestamp(),
    };
    if (decision === "Approved") applicationPatch.approvedAt = serverTimestamp();
    if (decision === "Rejected") applicationPatch.rejectedAt = serverTimestamp();
    transaction.update(applicationRef, applicationPatch);

    if (decision === "Approved") {
      transaction.update(driverRef, {
        accountStatus: ACCOUNT_STATUSES.APPROVED,
        approvalStatus: "Approved",
        approvalReviewedAt: serverTimestamp(),
        approvalReviewedBy: adminId,
        updatedAt: serverTimestamp(),
      });
    }
    if (decision === "Rejected") {
      transaction.update(driverRef, {
        accountStatus: ACCOUNT_STATUSES.REJECTED,
        approvalStatus: "Rejected",
        approvalReviewedAt: serverTimestamp(),
        approvalReviewedBy: adminId,
        updatedAt: serverTimestamp(),
      });
    }
    writeActivity(transaction, adminId, "driver-application-reviewed", "driverApplication", applicationId, `Driver application marked ${decision}.`, { decision });
  });
};

export const changeAccountStatus = async ({ adminId, targetUser, nextStatus, reason, activeAssignments = [] }) => {
  if (!Object.values(ACCOUNT_STATUSES).includes(nextStatus)) throw new Error("Choose a supported account status.");
  if (!hasText(reason, 3)) throw new Error("A reason of at least 3 characters is required.");
  if (!targetUser?.id) throw new Error("Select an account first.");
  if (targetUser.id === adminId) throw new Error("You cannot change your own account status.");
  const conflicts = getUserMissionConflicts(targetUser.id, activeAssignments);
  if ([ACCOUNT_STATUSES.DEACTIVATED, ACCOUNT_STATUSES.SUSPENDED, ACCOUNT_STATUSES.DISABLED].includes(nextStatus) && conflicts.length) {
    throw new Error("Resolve this Driver's active mission before changing this account status.");
  }

  await runTransaction(db, async (transaction) => {
    const targetRef = doc(db, FIRESTORE_COLLECTIONS.USERS, targetUser.id);
    const targetSnapshot = await transaction.get(targetRef);
    if (!targetSnapshot.exists()) throw new Error("This profile no longer exists.");
    const previousStatus = targetSnapshot.data().accountStatus || ACCOUNT_STATUSES.ACTIVE;
    const patch = {
      accountStatus: nextStatus,
      previousAccountStatus: previousStatus,
      accountStatusChangedAt: serverTimestamp(),
      accountStatusChangedBy: adminId,
      accountStatusReason: reason.trim(),
      updatedAt: serverTimestamp(),
    };
    if (nextStatus === ACCOUNT_STATUSES.DEACTIVATED) {
      patch.deactivatedAt = serverTimestamp();
      patch.deactivatedBy = adminId;
      patch.deactivationReason = reason.trim();
      if (targetSnapshot.data().role === ROLES.DRIVER) patch.availability = "Unavailable";
    }
    if (previousStatus === ACCOUNT_STATUSES.DEACTIVATED && nextStatus !== ACCOUNT_STATUSES.DEACTIVATED) {
      patch.restoredAt = serverTimestamp();
      patch.restoredBy = adminId;
      patch.restorationReason = reason.trim();
    }
    transaction.update(targetRef, patch);
    writeActivity(transaction, adminId, "account-status-changed", "user", targetUser.id, `${getProfileName(targetUser)} status changed to ${nextStatus}.`, { previousStatus, nextStatus, reason: reason.trim() });
  });
};

export const changeUserRole = async ({ adminId, targetUser, nextRole, reason, activeAssignments = [] }) => {
  if (!ROLE_OPTIONS.includes(nextRole)) throw new Error("Choose a supported role.");
  if (!hasText(reason, 3)) throw new Error("A reason of at least 3 characters is required.");
  if (!targetUser?.id || targetUser.id === adminId) throw new Error("You cannot change your own role.");
  if (targetUser.role === ROLES.DRIVER && targetUser.role !== nextRole && getUserMissionConflicts(targetUser.id, activeAssignments).length) {
    throw new Error("Resolve this Driver's active mission before changing roles.");
  }
  await runTransaction(db, async (transaction) => {
    const targetRef = doc(db, FIRESTORE_COLLECTIONS.USERS, targetUser.id);
    const snapshot = await transaction.get(targetRef);
    if (!snapshot.exists()) throw new Error("This profile no longer exists.");
    const previousRole = snapshot.data().role;
    transaction.update(targetRef, { role: nextRole, previousRole, roleChangedAt: serverTimestamp(), roleChangedBy: adminId, roleChangeReason: reason.trim(), updatedAt: serverTimestamp() });
    writeActivity(transaction, adminId, "role-changed", "user", targetUser.id, `${getProfileName(targetUser)} role changed to ${nextRole}.`, { previousRole, nextRole, reason: reason.trim() });
  });
};

export const updateDispatcherScope = async ({ adminId, targetUser, serviceAreas, operationalPhone, office }) => {
  const uniqueAreas = [...new Set(serviceAreas.filter(Boolean))];
  await runTransaction(db, async (transaction) => {
    const targetRef = doc(db, FIRESTORE_COLLECTIONS.USERS, targetUser.id);
    const snapshot = await transaction.get(targetRef);
    if (!snapshot.exists() || snapshot.data().role !== ROLES.DISPATCHER) throw new Error("This profile is not a Dispatcher.");
    transaction.update(targetRef, { serviceAreas: uniqueAreas, operationalPhone: operationalPhone.trim(), office: office.trim(), scopeChangedAt: serverTimestamp(), scopeChangedBy: adminId, updatedAt: serverTimestamp() });
    writeActivity(transaction, adminId, "dispatcher-scope-changed", "user", targetUser.id, `Dispatcher scope updated for ${getProfileName(targetUser)}.`, { serviceAreas: uniqueAreas });
  });
};

export const createStaffInvitation = async ({ adminId, email, displayName, intendedRole, barangay, serviceAreas, operationalPhone }) => {
  const normalizedEmail = email.trim().toLowerCase();
  if (!/^\S+@\S+\.\S+$/.test(normalizedEmail)) throw new Error("Enter a valid staff email address.");
  if (intendedRole !== ROLES.DISPATCHER) throw new Error("Only Dispatcher invitations are supported from this client.");
  if (!hasText(displayName, 2)) throw new Error("Enter the staff member's display name.");
  const existing = await getDocs(query(collection(db, FIRESTORE_COLLECTIONS.STAFF_INVITATIONS), where("email", "==", normalizedEmail), where("status", "==", ACTIVE_INVITATION_STATUS), limit(1)));
  if (!existing.empty) throw new Error("A pending invitation already exists for this email address.");
  const invitationRef = doc(collection(db, FIRESTORE_COLLECTIONS.STAFF_INVITATIONS));
  await setDoc(invitationRef, { email: normalizedEmail, intendedRole, displayName: displayName.trim(), barangay: barangay.trim(), serviceAreas: [...new Set(serviceAreas.filter(Boolean))], operationalPhone: operationalPhone.trim(), status: ACTIVE_INVITATION_STATUS, createdBy: adminId, createdAt: serverTimestamp(), expiresAt: null });
};

export const requestPermanentDeletion = async ({ adminId, targetUser, reason }) => {
  if (!targetUser?.id || targetUser.id === adminId) throw new Error("You cannot request deletion of your own Admin account here.");
  if (!hasText(reason, 3)) throw new Error("A deletion-request reason is required.");
  const requestRef = doc(collection(db, FIRESTORE_COLLECTIONS.DELETION_REQUESTS));
  await setDoc(requestRef, { targetUserId: targetUser.id, requestedBy: adminId, reason: reason.trim(), status: "Pending backend processing", requestedAt: serverTimestamp() });
};

export const saveMaintenanceRecord = async ({ adminId, vehicle, form, activeAssignments = [] }) => {
  if (!vehicle?.id) throw new Error("Select a vehicle first.");
  if (!Object.values(VEHICLE_MAINTENANCE_STATUSES).includes(form.status)) throw new Error("Choose a supported maintenance status.");
  if (!hasText(form.maintenanceType, 2) || !hasText(form.description, 3)) throw new Error("Maintenance type and description are required.");
  if (form.status === VEHICLE_MAINTENANCE_STATUSES.COMPLETED && !form.completedAt) throw new Error("A completed maintenance record needs a completion date.");
  const assignmentConflict = activeAssignments.some((assignment) => assignment.vehicleId === vehicle.id && isActiveMission(assignment));
  if ([VEHICLE_MAINTENANCE_STATUSES.SCHEDULED, VEHICLE_MAINTENANCE_STATUSES.IN_PROGRESS].includes(form.status) && assignmentConflict) throw new Error("Resolve the active vehicle mission before starting maintenance.");
  const maintenanceRef = doc(collection(db, FIRESTORE_COLLECTIONS.VEHICLE_MAINTENANCE));
  await runTransaction(db, async (transaction) => {
    const vehicleRef = doc(db, FIRESTORE_COLLECTIONS.VEHICLES, vehicle.id);
    const vehicleSnapshot = await transaction.get(vehicleRef);
    if (!vehicleSnapshot.exists()) throw new Error("This vehicle no longer exists.");
    transaction.set(maintenanceRef, { vehicleId: vehicle.id, maintenanceType: form.maintenanceType.trim(), description: form.description.trim(), reportedIssues: form.reportedIssues.trim(), serviceProvider: form.serviceProvider.trim(), cost: Number(form.cost) || 0, odometer: form.odometer.trim(), status: form.status, startedAt: form.startedAt || null, completedAt: form.completedAt || null, nextServiceDate: form.nextServiceDate || null, createdBy: adminId, createdAt: serverTimestamp(), updatedAt: serverTimestamp() });
    const activeMaintenance = [VEHICLE_MAINTENANCE_STATUSES.SCHEDULED, VEHICLE_MAINTENANCE_STATUSES.IN_PROGRESS, VEHICLE_MAINTENANCE_STATUSES.REPORTED].includes(form.status);
    transaction.update(vehicleRef, { maintenanceStatus: form.status, status: activeMaintenance ? "Under Maintenance" : vehicleSnapshot.data().status || "Inactive", lastMaintenanceDate: form.completedAt || null, nextMaintenanceDate: form.nextServiceDate || null, updatedAt: serverTimestamp() });
    writeActivity(transaction, adminId, "vehicle-maintenance-created", "vehicle", vehicle.id, `Maintenance record added for ${vehicleSnapshot.data().name || vehicle.id}.`, { maintenanceStatus: form.status });
  });
};

export const saveSystemSettings = async ({ adminId, settings }) => {
  const allowedBarangays = [...new Set((settings.supportedBarangays || []).filter(Boolean))];
  const categories = [...new Set((settings.requestCategories || []).filter((item) => hasText(item, 2)))];
  const vehicleTypes = [...new Set((settings.vehicleTypes || []).filter((item) => hasText(item, 2)))];
  if (!hasText(settings.publicOfficePhone, 7)) throw new Error("Enter a public office phone number.");
  await setDoc(doc(db, FIRESTORE_COLLECTIONS.SYSTEM_SETTINGS, "operational"), { supportedBarangays: allowedBarangays, requestCategories: categories, vehicleTypes, publicOfficePhone: settings.publicOfficePhone.trim(), maintenanceReminderDays: Math.max(1, Number(settings.maintenanceReminderDays) || 30), updatedAt: serverTimestamp(), updatedBy: adminId }, { merge: true });
};